"""init schema

Revision ID: 7dbc18758246
Revises: 
Create Date: 2026-09-16 15:36:10.940453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbc18758246'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_request_nonces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'nonce', name='uq_device_nonce')
    )
    with op.batch_alter_table('device_request_nonces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_request_nonces_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_request_nonces_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_request_nonces_id'), ['id'], unique=False)

    op.create_table('login_attempt_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('lock_until', sa.DateTime(), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempt_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempt_states_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempt_states_username'), ['username'], unique=True)

    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('text_model', sa.String(length=128), nullable=True),
    sa.Column('vision_model', sa.String(length=128), nullable=True),
    sa.Column('supports_text', sa.Boolean(), nullable=True),
    sa.Column('supports_vision', sa.Boolean(), nullable=True),
    sa.Column('is_active_text', sa.Boolean(), nullable=True),
    sa.Column('is_active_vision', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_configs_provider'), ['provider'], unique=False)

    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('runtime_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=96), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runtime_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runtime_locks_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_locks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_locks_name'), ['name'], unique=True)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_code', sa.String(length=64), nullable=False),
    sa.Column('tenant_name', sa.String(length=128), nullable=False),
    sa.Column('contact_name', sa.String(length=128), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_tenant_code'), ['tenant_code'], unique=True)

    op.create_table('device_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_code', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('envelope', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'message_id', name='uq_device_message_id')
    )
    with op.batch_alter_table('device_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_messages_device_code'), ['device_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_messages_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_messages_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_messages_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_messages_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_messages_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_messages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('device_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('smoke', sa.Float(), nullable=True),
    sa.Column('co', sa.Float(), nullable=True),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_telemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_telemetry_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_telemetry_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_telemetry_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('duty_handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('handover_time', sa.DateTime(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('from_person', sa.String(length=64), nullable=True),
    sa.Column('to_person', sa.String(length=64), nullable=True),
    sa.Column('handover_items', sa.Text(), nullable=True),
    sa.Column('pending_matters', sa.Text(), nullable=True),
    sa.Column('equipment_status', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duty_handovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duty_handovers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_handovers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('duty_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('shift_name', sa.String(length=64), nullable=True),
    sa.Column('duty_person', sa.String(length=64), nullable=True),
    sa.Column('weather', sa.String(length=32), nullable=True),
    sa.Column('alarm_count', sa.Integer(), nullable=True),
    sa.Column('handled_count', sa.Integer(), nullable=True),
    sa.Column('inspection_count', sa.Integer(), nullable=True),
    sa.Column('abnormal_count', sa.Integer(), nullable=True),
    sa.Column('equipment_status', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duty_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duty_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_records_record_date'), ['record_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('duty_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('shift_name', sa.String(length=64), nullable=False),
    sa.Column('shift_type', sa.String(length=32), nullable=True),
    sa.Column('start_time', sa.String(length=16), nullable=True),
    sa.Column('end_time', sa.String(length=16), nullable=True),
    sa.Column('duty_date', sa.Date(), nullable=True),
    sa.Column('persons', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duty_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duty_shifts_duty_date'), ['duty_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_shifts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_shifts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('emergency_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=256), nullable=False),
    sa.Column('plan_type', sa.String(length=64), nullable=True),
    sa.Column('plan_level', sa.String(length=32), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('building_name', sa.String(length=128), nullable=True),
    sa.Column('responsible_person', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('procedures', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_plans_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('emergency_supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('supply_name', sa.String(length=128), nullable=False),
    sa.Column('supply_type', sa.String(length=64), nullable=True),
    sa.Column('specification', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('manager', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_supplies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_supplies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_supplies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('emergency_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(length=128), nullable=False),
    sa.Column('team_type', sa.String(length=64), nullable=True),
    sa.Column('leader', sa.String(length=64), nullable=True),
    sa.Column('leader_phone', sa.String(length=32), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('members', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_teams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_teams_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('evacuation_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('route_name', sa.String(length=128), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('building_name', sa.String(length=128), nullable=True),
    sa.Column('floor', sa.String(length=32), nullable=True),
    sa.Column('start_point', sa.String(length=256), nullable=True),
    sa.Column('end_point', sa.String(length=256), nullable=True),
    sa.Column('route_path', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evacuation_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evacuation_routes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evacuation_routes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('hardware_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('event_code', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('event_name', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hardware_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hardware_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hardware_events_event_code'), ['event_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_hardware_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_hardware_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hardware_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_hardware_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('inspection_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_code', sa.String(length=64), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('hazards', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('agent_steps', sa.Text(), nullable=True),
    sa.Column('used_vision_api', sa.Boolean(), nullable=True),
    sa.Column('used_text_model_api', sa.Boolean(), nullable=True),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_records_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_records_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('key_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('unit_name', sa.String(length=256), nullable=False),
    sa.Column('unit_code', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('legal_person', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('building_area', sa.Integer(), nullable=True),
    sa.Column('staff_count', sa.Integer(), nullable=True),
    sa.Column('fire_manager', sa.String(length=64), nullable=True),
    sa.Column('fire_phone', sa.String(length=32), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('last_check_date', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('key_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_units_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_key_units_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('real_name', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('fail_reason', sa.String(length=255), nullable=True),
    sa.Column('login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_login_at'), ['login_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_username'), ['username'], unique=False)

    op.create_table('maintenance_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('qualification', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_companies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_companies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('org_code', sa.String(length=64), nullable=False),
    sa.Column('org_name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('org_type', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=128), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_org_code'), ['org_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('risk_update_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('record_code', sa.String(length=64), nullable=False),
    sa.Column('building_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('old_score', sa.Integer(), nullable=True),
    sa.Column('new_score', sa.Integer(), nullable=True),
    sa.Column('change', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('related_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_update_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_update_records_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_update_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_update_records_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_update_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_update_records_record_code'), ['record_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_risk_update_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('role_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_role_code'), ['role_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('unit_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=256), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('inspector', sa.String(length=64), nullable=True),
    sa.Column('inspection_type', sa.String(length=64), nullable=True),
    sa.Column('items_checked', sa.Integer(), nullable=True),
    sa.Column('items_passed', sa.Integer(), nullable=True),
    sa.Column('problems_found', sa.Integer(), nullable=True),
    sa.Column('rectification_required', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_inspections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_inspections_inspection_date'), ['inspection_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_inspections_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_inspections_unit_id'), ['unit_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('password_salt', sa.String(length=128), nullable=False),
    sa.Column('real_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('ai_review_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=24), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('hazards', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=64), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_review_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_review_tasks_confidence'), ['confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_review_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_review_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_review_tasks_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_review_tasks_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_review_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_review_tasks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('background_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=48), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.String(length=255), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('done_items', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_background_tasks_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('building_code', sa.String(length=64), nullable=False),
    sa.Column('building_name', sa.String(length=128), nullable=False),
    sa.Column('building_type', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buildings_building_code'), ['building_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_buildings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buildings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_buildings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('llm_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('purpose', sa.String(length=48), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('priced', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_call_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('status_before', sa.String(length=64), nullable=True),
    sa.Column('status_after', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_hash'), ['hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('report_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('report_no', sa.String(length=64), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=True),
    sa.Column('report_format', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_by_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_artifacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_artifacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_artifacts_report_no'), ['report_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_report_artifacts_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_artifacts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('fault_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('building_name', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('ticket_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('assignee_name', sa.String(length=64), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('reporter_name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('handle_result', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('review_result', sa.String(length=32), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fault_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fault_tickets_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fault_tickets_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fault_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fault_tickets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fault_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_fault_tickets_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_fault_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fault_tickets_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fault_tickets_ticket_type'), ['ticket_type'], unique=False)

    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('floor_name', sa.String(length=128), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('floor_plan_image', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_floors_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_floors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_floors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_floors_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_floors_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('maintenance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('plan_no', sa.String(length=64), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('device_count', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_date', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['maintenance_companies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_plans_plan_no'), ['plan_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_maintenance_plans_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('device_code', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('floor_x', sa.Float(), nullable=True),
    sa.Column('floor_y', sa.Float(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('last_maintenance', sa.Date(), nullable=True),
    sa.Column('next_maintenance', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_inspection_time', sa.DateTime(), nullable=True),
    sa.Column('device_secret', sa.String(length=128), nullable=True),
    sa.Column('secret_issued_at', sa.DateTime(), nullable=True),
    sa.Column('ingest_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_device_code'), ['device_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('record_no', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('building_name', sa.String(length=128), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('device_count', sa.Integer(), nullable=True),
    sa.Column('fault_count', sa.Integer(), nullable=True),
    sa.Column('maintainer', sa.String(length=64), nullable=True),
    sa.Column('maintain_date', sa.Date(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['maintenance_companies.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['maintenance_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_record_no'), ['record_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_maintenance_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('alert_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('alert_code', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_code', sa.String(length=64), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('building_name', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('alert_value', sa.Float(), nullable=True),
    sa.Column('alert_unit', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_analysis', sa.Text(), nullable=True),
    sa.Column('workorder_id', sa.Integer(), nullable=True),
    sa.Column('dedup_key', sa.String(length=160), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('handle_result', sa.Text(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('telemetry_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workorder_id'], ['fault_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_records_alert_code'), ['alert_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_alert_records_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_records_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_records_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_records_escalated'), ['escalated'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_records_merged_into_id'), ['merged_into_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_records_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_records_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_records_workorder_id'), ['workorder_id'], unique=False)

    op.create_table('video_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('channel_code', sa.String(length=64), nullable=False),
    sa.Column('channel_name', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('channel_no', sa.String(length=16), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_cipher', sa.Text(), nullable=True),
    sa.Column('snapshot_path', sa.String(length=255), nullable=True),
    sa.Column('rtsp_url', sa.String(length=512), nullable=True),
    sa.Column('ptz_enabled', sa.Boolean(), nullable=True),
    sa.Column('verify_tls', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('last_probe_at', sa.DateTime(), nullable=True),
    sa.Column('last_snapshot_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('device_model', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel_code', name='uq_video_channel_code')
    )
    with op.batch_alter_table('video_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_channels_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_channels_channel_code'), ['channel_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_channels_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_channels_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_channels_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_channels_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_channels_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_channels_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_channels_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_channels_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_video_channels_status'))
        batch_op.drop_index(batch_op.f('ix_video_channels_platform'))
        batch_op.drop_index(batch_op.f('ix_video_channels_id'))
        batch_op.drop_index(batch_op.f('ix_video_channels_enabled'))
        batch_op.drop_index(batch_op.f('ix_video_channels_device_id'))
        batch_op.drop_index(batch_op.f('ix_video_channels_created_at'))
        batch_op.drop_index(batch_op.f('ix_video_channels_channel_code'))
        batch_op.drop_index(batch_op.f('ix_video_channels_building_id'))

    op.drop_table('video_channels')
    with op.batch_alter_table('alert_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_records_workorder_id'))
        batch_op.drop_index(batch_op.f('ix_alert_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_alert_records_status'))
        batch_op.drop_index(batch_op.f('ix_alert_records_severity'))
        batch_op.drop_index(batch_op.f('ix_alert_records_merged_into_id'))
        batch_op.drop_index(batch_op.f('ix_alert_records_id'))
        batch_op.drop_index(batch_op.f('ix_alert_records_escalated'))
        batch_op.drop_index(batch_op.f('ix_alert_records_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_alert_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_alert_records_building_id'))
        batch_op.drop_index(batch_op.f('ix_alert_records_alert_type'))
        batch_op.drop_index(batch_op.f('ix_alert_records_alert_code'))

    op.drop_table('alert_records')
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_record_no'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_id'))

    op.drop_table('maintenance_records')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_devices_status'))
        batch_op.drop_index(batch_op.f('ix_devices_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))
        batch_op.drop_index(batch_op.f('ix_devices_device_type'))
        batch_op.drop_index(batch_op.f('ix_devices_device_code'))
        batch_op.drop_index(batch_op.f('ix_devices_created_at'))
        batch_op.drop_index(batch_op.f('ix_devices_building_id'))

    op.drop_table('devices')
    with op.batch_alter_table('maintenance_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_plans_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_plans_plan_no'))
        batch_op.drop_index(batch_op.f('ix_maintenance_plans_id'))

    op.drop_table('maintenance_plans')
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_floors_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_floors_status'))
        batch_op.drop_index(batch_op.f('ix_floors_id'))
        batch_op.drop_index(batch_op.f('ix_floors_created_at'))
        batch_op.drop_index(batch_op.f('ix_floors_building_id'))

    op.drop_table('floors')
    with op.batch_alter_table('fault_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fault_tickets_ticket_type'))
        batch_op.drop_index(batch_op.f('ix_fault_tickets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_fault_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_fault_tickets_source'))
        batch_op.drop_index(batch_op.f('ix_fault_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_fault_tickets_id'))
        batch_op.drop_index(batch_op.f('ix_fault_tickets_created_at'))
        batch_op.drop_index(batch_op.f('ix_fault_tickets_building_id'))
        batch_op.drop_index(batch_op.f('ix_fault_tickets_assignee_id'))

    op.drop_table('fault_tickets')
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_created_at'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_category'))

    op.drop_table('uploaded_files')
    with op.batch_alter_table('report_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_artifacts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_report_artifacts_report_type'))
        batch_op.drop_index(batch_op.f('ix_report_artifacts_report_no'))
        batch_op.drop_index(batch_op.f('ix_report_artifacts_id'))
        batch_op.drop_index(batch_op.f('ix_report_artifacts_created_at'))

    op.drop_table('report_artifacts')
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_target_type'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_source'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_seq'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_module'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_level'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_hash'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_created_at'))

    op.drop_table('operation_logs')
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_status'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_purpose'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_model'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_id'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_created_at'))

    op.drop_table('llm_call_logs')
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buildings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_buildings_status'))
        batch_op.drop_index(batch_op.f('ix_buildings_id'))
        batch_op.drop_index(batch_op.f('ix_buildings_building_code'))

    op.drop_table('buildings')
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_task_id'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_lease_expires_at'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_created_at'))

    op.drop_table('background_tasks')
    with op.batch_alter_table('ai_review_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_review_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ai_review_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_ai_review_tasks_source'))
        batch_op.drop_index(batch_op.f('ix_ai_review_tasks_record_id'))
        batch_op.drop_index(batch_op.f('ix_ai_review_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_ai_review_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_review_tasks_confidence'))

    op.drop_table('ai_review_tasks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('unit_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_inspections_unit_id'))
        batch_op.drop_index(batch_op.f('ix_unit_inspections_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_unit_inspections_inspection_date'))
        batch_op.drop_index(batch_op.f('ix_unit_inspections_id'))

    op.drop_table('unit_inspections')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_roles_role_code'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('risk_update_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_update_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_risk_update_records_record_code'))
        batch_op.drop_index(batch_op.f('ix_risk_update_records_id'))
        batch_op.drop_index(batch_op.f('ix_risk_update_records_event_type'))
        batch_op.drop_index(batch_op.f('ix_risk_update_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_risk_update_records_building_id'))

    op.drop_table('risk_update_records')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_organizations_org_code'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('maintenance_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_companies_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_companies_id'))

    op.drop_table('maintenance_companies')
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_logs_username'))
        batch_op.drop_index(batch_op.f('ix_login_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_login_logs_status'))
        batch_op.drop_index(batch_op.f('ix_login_logs_login_at'))
        batch_op.drop_index(batch_op.f('ix_login_logs_id'))

    op.drop_table('login_logs')
    with op.batch_alter_table('key_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_units_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_key_units_id'))

    op.drop_table('key_units')
    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_records_risk_level'))
        batch_op.drop_index(batch_op.f('ix_inspection_records_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_records_device_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_records_created_at'))

    op.drop_table('inspection_records')
    with op.batch_alter_table('hardware_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hardware_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_hardware_events_status'))
        batch_op.drop_index(batch_op.f('ix_hardware_events_id'))
        batch_op.drop_index(batch_op.f('ix_hardware_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_hardware_events_event_code'))
        batch_op.drop_index(batch_op.f('ix_hardware_events_created_at'))

    op.drop_table('hardware_events')
    with op.batch_alter_table('evacuation_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evacuation_routes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_evacuation_routes_id'))

    op.drop_table('evacuation_routes')
    with op.batch_alter_table('emergency_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_teams_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_teams_id'))

    op.drop_table('emergency_teams')
    with op.batch_alter_table('emergency_supplies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_supplies_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_supplies_id'))

    op.drop_table('emergency_supplies')
    with op.batch_alter_table('emergency_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_plans_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_plans_id'))

    op.drop_table('emergency_plans')
    with op.batch_alter_table('duty_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duty_shifts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_duty_shifts_id'))
        batch_op.drop_index(batch_op.f('ix_duty_shifts_duty_date'))

    op.drop_table('duty_shifts')
    with op.batch_alter_table('duty_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duty_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_duty_records_record_date'))
        batch_op.drop_index(batch_op.f('ix_duty_records_id'))

    op.drop_table('duty_records')
    with op.batch_alter_table('duty_handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duty_handovers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_duty_handovers_id'))

    op.drop_table('duty_handovers')
    with op.batch_alter_table('device_telemetry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_telemetry_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_device_telemetry_id'))
        batch_op.drop_index(batch_op.f('ix_device_telemetry_device_id'))

    op.drop_table('device_telemetry')
    with op.batch_alter_table('device_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_device_messages_status'))
        batch_op.drop_index(batch_op.f('ix_device_messages_source'))
        batch_op.drop_index(batch_op.f('ix_device_messages_received_at'))
        batch_op.drop_index(batch_op.f('ix_device_messages_message_id'))
        batch_op.drop_index(batch_op.f('ix_device_messages_kind'))
        batch_op.drop_index(batch_op.f('ix_device_messages_id'))
        batch_op.drop_index(batch_op.f('ix_device_messages_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_messages_device_code'))

    op.drop_table('device_messages')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_tenant_code'))
        batch_op.drop_index(batch_op.f('ix_tenants_id'))

    op.drop_table('tenants')
    with op.batch_alter_table('runtime_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_locks_name'))
        batch_op.drop_index(batch_op.f('ix_runtime_locks_id'))
        batch_op.drop_index(batch_op.f('ix_runtime_locks_expires_at'))

    op.drop_table('runtime_locks')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_expires_at'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_configs_provider'))
        batch_op.drop_index(batch_op.f('ix_model_configs_id'))

    op.drop_table('model_configs')
    with op.batch_alter_table('login_attempt_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempt_states_username'))
        batch_op.drop_index(batch_op.f('ix_login_attempt_states_id'))

    op.drop_table('login_attempt_states')
    with op.batch_alter_table('device_request_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_request_nonces_id'))
        batch_op.drop_index(batch_op.f('ix_device_request_nonces_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_request_nonces_created_at'))

    op.drop_table('device_request_nonces')
    # ### end Alembic commands ###
